---
- name: Pull docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull karishma056/scientific_calc
      
    - name: running container
      shell: docker run -it -d karishma056/scientific_calc

# ---
# - name: Pull Docker image of Calculator
#   hosts: all
#   vars:
#     ansible_python_interpreter: /usr/bin/python3
#   tasks:
#     - name: Pull image
#       docker_image:
#         name: karishma056/scientific_calc:latest
#         source: pull
#     - name: Running container
# shell: docker run -it -d karishma056/scientific_calc
