#Ansible Playbook specifying the commands to execute on remote server.
---
- name: Pull docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
#   Starts docker in remote server.
    - name: Start docker service
      service:
        name: docker
        state: started

#  pulls the docker image from DockerHub repository: karishma056/scientific_calc
    - name: pull docker image
      shell: docker pull karishma056/scientific_calc

#  runs the pulled image and creates a container in remote server(configured in Ansible inventory)
    - name: running container
      shell: docker run -it -d karishma056/scientific_calc /bin/bash



